CLEAR_CHAT_BUTTON = r"body > main > div > div.flex.flex-col.md\:flex-col.md\:relative.w-full.max-w-\[900px\].bg-background.z-10.gap-2.md\:gap-6 > div > button.inline-flex.items-center.justify-center.whitespace-nowrap.rounded-md.text-sm.font-medium.ring-offset-background.transition-colors.focus-visible\:outline-none.disabled\:pointer-events-none.disabled\:opacity-50.underline-offset-4.h-10.p-0.text-muted-foreground.dark\:text-\[\#BCBCBC\].hover\:text-primaryaccent.dark\:hover\:text-primaryaccent.hover\:no-underline"
MODEL_DROPDOWN_SELECTOR = r"body > header > div.flex-1.flex.items-center.justify-center.md\:col-span-4.md\:col-start-2 > div > button"
QUERY_SELECTOR = "div.break-words"
RESPONSE_SELECTOR = "div.text-base"
PROMPT_SETTER_SELETOR = r"body > header > div.flex-1.flex.items-center.justify-center.md\:col-span-4.md\:col-start-2 > div > button.flex.gap-1.items-center.ml-1.px-2.sm\:px-3"
PROMPT_TEXTAREA_SELECTOR = r"#radix-\:r3\: > textarea"
END_TEXT_SELECTOR = r"body > main > div > div.flex.flex-col.md\:flex-col.md\:relative.w-full.max-w-\[900px\].bg-background.z-10.gap-2.md\:gap-6 > div > button.block.lg\:hidden > div > div"
QUERY_INPUT_SELECTOR = "#chat"
CHAT_INPUT_SELECTOR = "#chat"
QUERY_SUBMIT_SELECTOR = r"body > main > div > div.hidden.md\:block.w-full > div > div.order-2.md\:order-1 > form > div > button"
PROFILE_BUTTON_SELECTOR = r"#radix-\:r3\:"
ADVANCED_SETTING_SELECTOR = r"#radix-\:rf\:"
SYSTEM_PROMPT_BUTTON = r"button.py-1\.5:nth-child(1)"
SYSTEM_PROMPT_TEXTAREA = r"textarea.w-full:nth-child(2)"
PROMPT_SAVE_BUTTON_SELECTOR = r"html.__variable_b1da2a.__variable_aaf875.dark body.fixed.!inset-0.flex.flex-col.font-montserrat.selection:bg-selection.bg-background.text-foreground div#radix-:rl:.fixed.left-[50%].top-[50%].z-50.grid.max-w-xl.translate-x-[-50%].translate-y-[-50%].gap-4.border.bg-background.p-6.shadow-lg.duration-200.data-[state=open]:animate-in.data-[state=closed]:animate-out.data-[state=closed]:fade-out-0.data-[state=open]:fade-in-0.data-[state=closed]:zoom-out-95.data-[state=open]:zoom-in-95.data-[state=closed]:slide-out-to-left-1/2.data-[state=closed]:slide-out-to-top-[48%].data-[state=open]:slide-in-from-left-1/2.data-[state=open]:slide-in-from-top-[48%].sm:rounded-lg.w-full.h-full.md:max-w-[455px].md:h-auto div div.flex.items-center button.inline-flex.items-center.justify-center.whitespace-nowrap.rounded-md.text-sm.font-medium.ring-offset-background.transition-colors.focus-visible:outline-none.disabled:pointer-events-none.disabled:opacity-50.hover:bg-gray-600.dark:hover:bg-slate-200.h-10.px-4.py-2.ml-3.text-background.bg-foreground.dark:text-black.dark:bg-white"
COPY_BUTTON_SELECTOR = r"body > main > div > div.grow.w-full.overflow-auto.mt-2.flex.flex-col.md\:flex-col > div.flex.flex-col.\[word-break\:break-word\].mb-6 > div.flex.flex-col.font-normal.text-base.border-l.border-mutedaccent.px-5 > div.flex.flex-row.align-center.items-center.gap-4.pt-4 > div:nth-child(1) > svg"
MODEL_NAME_SELECTOR = r"body > header > div.flex-1.flex.items-center.justify-center.md\:col-span-4.md\:col-start-2 > div > button > p"

SIGNIN_BUTTON_SELECTOR = r"#radix-\:r6\:"
SIGNIN_BUTTON_TEXT = "Sign in to Groq"